<a href="https://colab.research.google.com/github/pawan76542987/python/blob/main/NumpyLec04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# agar np likha hai to numpy.array(1 , 2 , 3 ,4) likhne ki jarurat nahi hai np.array(1 , 2 , 3, 4) likhe sakte hain


In [ ]:
a = np.array([1 , 2 , 3 , 4 ,8 ]) # Yah ek simple NumPy array banata hai integers ke sath.
print(a) # Is array ko print karta hai.

# Agar 'a' array mein ek string value (e.g., '2') shamil kar den to kya hoga?
# NumPy automatic 'type promotion' karta hai. Jab array mein mixed data types hote hain (jaise ki int aur string),
# NumPy sabhi elements ko ek common, compatible data type mein badal deta hai.
# Is case mein, sabhi numbers ko string mein badal diya jayega tak ki poora array uniform ho.
a = np.array([1 , '2' , 3 , 4 ,8 ])
# Sabhi elements ko string data type ('<U21' ya similar string type) mein badal deta hai.
print(a) # Modified array ko print karta hai, jisme sabhi elements ab strings hain.

[1 2 3 4 8]
['1' '2' '3' '4' '8']


In [ ]:
# Q.1
# Yah ek NumPy array banata hai jisme alag-alag data type ke elements hain.
# NumPy mixed data types ko handle karne ke liye sabhi elements ko ek common type me convert kar deta hai,
# is case me string type ('<U32') me.
np_arr = np.array([3 , 3 , 2 , 3.3 , 'hello' , False])

# np_arr[-1] array ke aakhri element ko refer karta hai, jo ki yahan 'False' string ban chuka hai.
# bool() function us string ko boolean value me convert karta hai.
# Empty string '' ko chhodkar koi bhi non-empty string bool() me True return karti hai.
print(bool(np_arr[-1]))

True


In [ ]:
# यह एक 1D NumPy array बनाता है जिसमें 3 शून्य (zeros) होते हैं।
# a = np.zeros(3)

# print(a)

# NumPy arrays को मैट्रिक्स (matrix) की तरह भी उपयोग कर सकते हैं।

# यह एक 2D NumPy array (मैट्रिक्स) बनाता है जिसमें 3 पंक्तियों (rows) और 3 कॉलम (columns) होते हैं, सभी शून्य के साथ।
# b = np.zeros([3 ,3])

# print(b)

# यह एक 3D NumPy array बनाता है जिसमें 3 'गहराई', 3 पंक्तियाँ और 4 कॉलम होते हैं, सभी शून्य के साथ।
b = np.zeros([3 ,3,4])

# 3D array को प्रिंट करता है।
print(b)

# array के पहले एलिमेंट का डेटा टाइप प्रिंट करता है। डिफ़ॉल्ट रूप से, यह float होता है।
print(type(b[0][0][0]))

# हम इस array को पूर्णांक (integer) डेटा टाइप में भी बदल सकते हैं।
# यह एक नया 3D NumPy array बनाता है जिसमें 3 'गहराई', 3 पंक्तियाँ और 4 कॉलम होते हैं, सभी शून्य और पूर्णांक डेटा टाइप के साथ।
b = np.zeros([3 ,3,4 ],dtype=int)

# अब array के पहले एलिमेंट का डेटा टाइप प्रिंट करता है, जो अब पूर्णांक (int) होगा।
print(type(b[0][0][0]))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<class 'numpy.float64'>
<class 'numpy.int64'>


In [ ]:
# full
a = np.full(4,5,dtype=int)
print(a)

[5 5 5 5]


In [ ]:
# arange
a = np.arange(1 , 14 ,2)
# start , stop , jump
print(a)


[ 1  3  5  7  9 11 13]


In [ ]:
a = np.array([1 , 2 , 3 , 4 ,8 ]) # This line creates a NumPy array named 'a' with the specified integer values.
print(a) # This line prints the array 'a'.
print(a.size) # This line prints the total number of elements in the array 'a'.
print(a.shape) # This line prints the dimensions of the array 'a'. For a 1D array, it returns a tuple with the number of elements.
print(a.dtype) # This line prints the data type of the elements in the array 'a'.

[1 2 3 4 8]
5
(5,)
int64


In [ ]:
# This line generates an array of 4 random integers.
# The integers will be between 3 (inclusive) and 13 (exclusive).
a = np.random.randint(3 , 13 ,4)
print(a)

[ 5 10  8  9]


In [ ]:
# Yah do NumPy arrays banata hai, jinhe hum operations ke liye use karenge.
a = np.array([1 , 2 , 3 , 4 ,8 ]) # Pehla array 'a' integers ke sath.
b = np.array([1 , 3 , 8 , 2 ,4 ]) # Dusra array 'b' integers ke sath.

# Array ke har element ko dusre array ke corresponding element se multiply karta hai (element-wise multiplication).
print(a * b)

# Array ke har element ko dusre array ke corresponding element se divide karta hai (element-wise division).
print(a / b)

# Array ke har element ko ek scalar value (yahan 3) se multiply karta hai.
print(a * 3)



[ 1  6 24  8 32]
[1.         0.66666667 0.375      2.         2.        ]
[ 3  6  9 12 24]


In [ ]:
# ab list me same trye karenge

a = [1 , 2 , 3 , 4 ,  5, 6]
b = [2 , 4 ,5 , 6 ,7 , 8]

# Python lists ko seedha * operator se multiply nahi kar sakte. Isse error aati hai.
# Agar element-wise multiplication karna hai, toh loop ya list comprehension use karna hoga,
# ya phir NumPy arrays ka istemal karna hoga.
# print(a*b)  # Yeh line error degi: TypeError: can't multiply sequence by non-int of type 'list'

# List ko ek integer se multiply karne par, list ke elements multiply nahi hote,
# balki list khud utni baar repeat ho jaati hai.
# Jaise [1, 2]*2 ka result [1, 2, 1, 2] hoga.
print(a*2)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]


In [ ]:
# function re shape (yeh function array ke shape ko badalne ke liye use hota hai)

# Yah ek NumPy array 'a' banata hai jisme 6 random integers hain.
# Ye integers 3 (inclusive) se 12 (exclusive) ke beech honge.
a = np.random.randint(3 , 12 , 6)

# Original array 'a' ko print karta hai.
print(a)

# Array 'a' ko reshape karta hai ek nayi shape (2 rows aur 3 columns) mein.
# Naye array 'b' mein 2 rows aur 3 columns honge, aur elements 'a' se aayenge.
b = a.reshape(2,3)

# Reshaped array 'b' ko print karta hai.
print(b)

[ 6  6  8 10  4 10]
[[ 6  6  8]
 [10  4 10]]


In [59]:
# Yahan hum do NumPy arrays 'a' aur 'b' bana rahe hain integers ke sath.
# Pehla array 'a' mein kuch numbers hain.
a = np.array([1, 2, 3, 3, 4, 5, 6, 6])
# Dusra array 'b' mein bhi kuch numbers hain.
b = np.array([2, 3, 4, 5, 7, 8, 8, 9])

# --- Arrays ko jodna (Concatenation) ---
# np.concatenate() function do ya do se zyada arrays ko jodne (join karne) ke liye use hota hai.
# Yahan hum 'a' aur 'b' arrays ko ek saath jod rahe hain.
# Result ek naya, bada array hoga jisme 'a' ke elements ke baad 'b' ke elements honge.
# 'axis=0' (default) ka matlab hai ki arrays ko rows ke through joda ja raha hai (vertically for 1D arrays).
concat = np.concatenate((a, b))

# Bane hue concatenated array 'concat' ko print kar rahe hain.
print("Concatenated Array (concat):")
print(concat)

# --- Arrays ko Transpose karna ---
# np.transpose() function arrays ke dimensions ko palat deta hai.
# Yahan hum 'a' aur 'b' ko ek tuple ke roop mein de rahe hain, jise woh ek 2D array bana kar transpose karta hai.
# 'a' (1D) aur 'b' (1D) combine hokar ek (2, N) shape ka temporary array banate hain, jisse phir (N, 2) mein transpose kiya jata hai.
# Matlab, 'a' ke elements pehli row ban jayenge aur 'b' ke elements dusri row, phir rows aur columns swap ho jayenge.
tranc = np.transpose((a, b))

# Transposed array 'tranc' ko print kar rahe hain.
print("\nTransposed Array (tranc):")
print(tranc)


Concatenated Array (concat):
[1 2 3 3 4 5 6 6 2 3 4 5 7 8 8 9]

Transposed Array (tranc):
[[1 2]
 [2 3]
 [3 4]
 [3 5]
 [4 7]
 [5 8]
 [6 8]
 [6 9]]


In [60]:
# Yahan hum ek NumPy array 'a' bana rahe hain random integers ke sath.
# isme 6 random integers honge, jo 2 (inclusive) se 15 (exclusive) tak ki range mein honge.
a = np.random.randint(2, 15, 6)

# Yahan hum ek aur NumPy array 'b' bana rahe hain random integers ke sath.
# isme bhi 6 random integers honge, jo 1 (inclusive) se 19 (exclusive) tak ki range mein honge.
b = np.random.randint(1, 19, 6)

# Array 'a' ko print kar rahe hain, taki uske elements dekh saken.
print("Array 'a':", a)
# Array 'b' ko print kar rahe hain, taki uske elements dekh saken.
print("Array 'b':", b)

# np.where() function conditions ke basis par elements choose karta hai.
# Syntax: np.where(condition, value_if_true, value_if_false)
# Yahan, agar array 'b' ka corresponding element 2 se bada hai (b > 2),
# toh naye array 'c' mein 'b' ka woh element aayega.
# Agar condition false hai (b <= 2), toh 'a' ka corresponding element aayega.
c = np.where(b > 2, b, a)

# Naye array 'c' ko print kar rahe hain, jo conditions ke hisaab se banaya gaya hai.
print("Array 'c' (condition b > 2):", c)


[ 4 13 13 11  7  4]
[6 5 6 9 6 6]
[6 5 6 9 6 6]


In [66]:
# Q.2: Is code mein hum user se input lekar ek NumPy array banayenge
# aur phir us array par kuch basic statistical operations perform karenge.

# Ek khaali Python list banate hain, jisme user ke inputs store kiye jayenge.
lst = []

# Loop 7 baar chalega, har baar user se ek integer input lega.
for i in range(7):
  # User se input lete hain aur use integer mein convert karte hain.
  user_input = int(input(f"Enter integer {i+1}/7: "))
  # Convert kiye gaye integer ko 'lst' list mein add karte hain.
  lst.append(user_input)

  # Har input ke baad, current 'lst' ko ek NumPy array mein convert karte hain.
  # Aur us array ko print karte hain, taki har step par changes dikhen.
  a = np.array(lst)
  print("Current NumPy Array:", a)

# Jab loop khatam ho jayega (yaani 7 inputs mil jayenge),
# tab final NumPy array 'a' par statistical calculations karenge.

# Array 'a' mein sabse chhota (minimum) element print karte hain.
print("\nMinimum value in array 'a':", np.min(a))
# Array 'a' mein sabse bada (maximum) element print karte hain.
print("Maximum value in array 'a':", np.max(a))
# Array 'a' ke sabhi elements ka average (mean) print karte hain.
print("Mean (average) of array 'a':", np.mean(a))
# Array 'a' ke elements ka median (middle value) print karte hain.
print("Medianof array 'a':", np.median(a))
# Array 'a' ke elements ka standard deviation (pramaanik vichalan) print karte hain.
print("Standard Deviation of array 'a':", np.std(a))


Enter integer 1/7: 1
Current NumPy Array: [1]
Enter integer 2/7: 2
Current NumPy Array: [1 2]
Enter integer 3/7: 3
Current NumPy Array: [1 2 3]
Enter integer 4/7: 4
Current NumPy Array: [1 2 3 4]
Enter integer 5/7: 5
Current NumPy Array: [1 2 3 4 5]
Enter integer 6/7: 6
Current NumPy Array: [1 2 3 4 5 6]
Enter integer 7/7: 7
Current NumPy Array: [1 2 3 4 5 6 7]

Minimum value in array 'a': 1
Maximum value in array 'a': 7
Mean (average) of array 'a': 4.0
Median of array 'a': 4.0
Standard Deviation of array 'a': 2.0
